[project]
name = "dbt-subprocess-plugin"
version = "0.1.0"
description = "dbt plugin to add Python's subprocess module to dbt's `modules` context attribute"
readme = "README.md"
authors = [
    { name = "Tim Vergenz", email = "vergenzt@gmail.com" }
]
requires-python = ">=3.8"
dependencies = [
    "dbt-core>=1.6",
]

[dependency-groups]
dev = [
    "hatch>=1.14.2",
    "pytest>=8.3.5",
    "dbt-postgres",
    "tinypg>=0.3.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
